INSERT INTO atletas (nomeAtleta, sobrenomeAtleta, regioes_idRegiao, divisaoAtleta) VALUES
('WILLY', 'GEORGES', 8, 1),
('STEFANO', 'CAROSSO', 8, 1),
('LUKAS', 'ESSLINGER', 8, 1),
('STEPHANE', 'OSSANGA', 8, 1),
('GIANLUCA', 'STITZER', 8, 1),
('FABIO', 'BOTTEGHI', 8, 1),
('ATES', 'BORAN', 8, 1),
('JONAS', 'MUELLER', 8, 1),
('NICOLA', 'PETRUZZI', 8, 1),
('SAM', 'LUBBEN', 8, 1),
('STEFANO', 'MIGLIORINI', 8, 1),
('DAVIDE', 'ARICI', 8, 1),
('MARC', 'ORDEIG', 8, 1),
('ALEXANDER', 'ANASAGASTI', 8, 1),
('FREDERICK', 'HUSSON', 8, 1),
('FRANCISCO', 'GODINHO', 8, 1),
('JOAO', 'FERREIRA', 8, 1),
('RUBÉN', 'INSUA', 8, 1),
('TIAGO', 'SALES', 8, 1),
('PEDRO', 'BARTOLO', 8, 1),
('JASON', 'SMITH', 8, 1),
('ALAN', 'FOULIS', 8, 1),
('RUAN', 'DUVENAGE', 8, 1),
('PHIL', 'HESKETH', 8, 1),
('DANIEL', 'SHERBAKOV', 8, 1),
('ANTONY', 'MONKS', 8, 1),
('RICHARD', 'SMITH', 8, 1),
('BASEL', 'QATAMESH', 8, 1),
('BRANDON', 'JACOBS', 8, 1),
('JUSTIN', 'SWART', 8, 1),
('ELLIOT', 'SIMMONDS', 8, 1),
('ANDRÉ', 'HOUDET', 8, 1),
('RASMUS', 'ANDERSEN', 8, 1),
('MOHAMED ABOU', 'AUF', 8, 1),
('DEAN', 'SHAW', 8, 1),
('JACQUES', 'DU TOIT', 8, 1),
('ALEX', 'EVANS', 8, 1),
('ROB', 'SCHILLACI', 8, 1),
('AHMED', 'EID', 8, 1),
('YAVUZ', 'SENTURK', 8, 1),
('RITA', 'GARCÍA', 8, 0),
('JACQUELINE', 'DAHLSTRØM', 8, 0),
('THELMA', 'CHRISTOFOROU', 8, 0),
('ANA C.', 'CALDAS', 8, 0),
('ANNE CLAIRE', 'DREYFUS', 8, 0),
('ELIA', 'NAVARRO', 8, 0),
('SARA ALICIA FERNANDEZ', 'COSTAS', 8, 0),
('MANILA', 'PENNACCHIO', 8, 0),
('ALBA', 'ESTRADA', 8, 0),
('ALESSIA JOY', 'WÄLCHLI', 8, 0),
('TINA', 'MOEGLIN', 8, 0),
('MICHAELA', 'PALOVA', 8, 0),
('SABRINA', 'NUNES', 8, 0),
('URSULA', 'FASEL', 8, 0),
('CAROLE', 'CASTELLANI', 8, 0),
('MARINA', 'NOVELLI', 8, 0),
('ALIZEE', 'ANDREANI', 8, 0),
('MATILDE', 'ORLANDONI', 8, 0),
('LISA', 'EBLE', 8, 0),
('SUSANA', 'LOPEZ', 8, 0),
('JAMIE', 'GREENE', 8, 0),
('ODDRUN EIK', 'GYLFADOTTIR', 8, 0),
('EMILIA', 'LEPPÄNEN', 8, 0),
('STEPHANIE', 'CHUNG', 8, 0),
('CARMEN', 'BOSMANS', 8, 0),
('CELESTE', 'MARITZ', 8, 0),
('KARIN', 'BAALBAKI', 8, 0),
('MIA', 'ÅKERLUND', 8, 0),
('LAUREN', 'FISHER', 8, 0),
('JENNIFER', 'KOKK', 8, 0),
('DINA', 'SWIFT', 8, 0),
('JOANNE', 'MCGURK', 8, 0),
('MICHELLE', 'MERAND', 8, 0),
('NUHA', 'ALMARRI', 8, 0),
('JESS', 'TOWL', 8, 0),
('CELESTIE', 'ENGELBRECHT', 8, 0),
('FERN', 'CARVER', 8, 0),
('NICOLE', 'PETTEL', 8, 0),
('NIKITA-JENNA', 'VAN ROOYEN', 8, 0),
('MARY', 'JAMIESON', 8, 0)
;